import { useState } from 'react';

const experienceLevels = [;
  'Beginner (0-6 months)',;
  'Intermediate (6 months - 2 years)',;
  'Advanced (2+ years)',;
  'Athlete/Competitive';
];

const equipmentOptions = [;
  'Dumbbells',;
  'Barbell',;
  'Resistance bands',;
  'Kettlebells',;
  'Yoga mat',;
  'Pull-up bar',;
  'Cardio machine',;
  'Full gym access',;
  'Limited equipment';
];

export default function ClientQuestionnaireStep1({ initialData, onNext, onBack, isSubmitting }) {;
  const [formData, setFormData] = useState({;
    age: initialData?.age || '',;
    gender: initialData?.gender || '',;
    experienceLevel: initialData?.experienceLevel || '',;
    height: initialData?.height || '',;
    weight: initialData?.weight || '',;
    timezone: initialData?.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone,;
    trainingPreference: initialData?.trainingPreference || ['online'],;
    weeklyTimeAvailability: initialData?.weeklyTimeAvailability || '',;
    equipmentAccess: initialData?.equipmentAccess || [];
  });

  const handleChange = (e) => {;
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleCheckboxChange = (name, value, checked) => {;
    setFormData(prev => {;
      const current = prev[name] || [];
      if (checked) {;
        return { ...prev, [name]: [...current, value] };
      } else {;
        return { ...prev, [name]: current.filter(item => item !== value) };
      };
    });
  };

  const handleSubmit = (e) => {;
    e.preventDefault();
    onNext(formData);
  };

  return (;
    <form onSubmit={handleSubmit} className="space-y-6">;
      <h2 className="text-2xl font-bold text-gray-800">Basic Information</h2>;
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">;
        <div>;
          <label className="block text-sm font-medium text-gray-700 mb-1">;
            Age (optional);
          </label>;
          <input;
            type="number";
            name="age";
            value={formData.age};
            onChange={handleChange};
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500";
            min="16";
            max="100";
          />;
        </div>;

        <div>;
          <label className="block text-sm font-medium text-gray-700 mb-1">;
            Gender (optional);
          </label>;
          <select;
            name="gender";
            value={formData.gender};
            onChange={handleChange};
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500";
          >;
            <option value="">Prefer not to say</option>;
            <option value="Male">Male</option>;
            <option value="Female">Female</option>;
            <option value="Non-binary">Non-binary</option>;
            <option value="Other">Other</option>;
          </select>;
        </div>;

        <div>;
          <label className="block text-sm font-medium text-gray-700 mb-1">;
            Fitness Experience Level *;
          </label>;
          <select;
            name="experienceLevel";
            value={formData.experienceLevel};
            onChange={handleChange};
            required;
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500";
          >;
            <option value="">Select your experience level</option>;
            {experienceLevels.map(level => (;
              <option key={level} value={level}>{level}</option>;
            ))};
          </select>;
        </div>;

        <div>;
          <label className="block text-sm font-medium text-gray-700 mb-1">;
            Height (optional);
          </label>;
          <input;
            type="text";
            name="height";
            value={formData.height};
            onChange={handleChange};
            placeholder="e.g., 5'9&quot;";
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500";
          />;
        </div>;

        <div>;
          <label className="block text-sm font-medium text-gray-700 mb-1">;
            Weight (optional);
          </label>;
          <input;
            type="text";
            name="weight";
            value={formData.weight};
            onChange={handleChange};
            placeholder="e.g., 160 lbs";
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500";
          />;
        </div>;

        <div>;
          <label className="block text-sm font-medium text-gray-700 mb-1">;
            Timezone *;
          </label>;
          <input;
            type="text";
            name="timezone";
            value={formData.timezone};
            onChange={handleChange};
            required;
            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 bg-gray-50";
            readOnly;
          />;
          <p className="mt-1 text-sm text-gray-500">Automatically detected</p>;
        </div>;
      </div>;

      <div>;
        <label className="block text-sm font-medium text-gray-700 mb-2">;
          Training Preference *;
        </label>;
        <div className="space-y-2">;
          {['online', 'in-person'].map(preference => (;
            <label key={preference} className="flex items-center">;
              <input;
                type="checkbox";
                checked={formData.trainingPreference.includes(preference)};
                onChange={(e) => handleCheckboxChange('trainingPreference', preference, e.target.checked)};
                className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded";
              />;
              <span className="ml-2 text-gray-700 capitalize">{preference.replace('-', ' ')}</span>;
            </label>;
          ))};
        </div>;
      </div>;

      <div>;
        <label className="block text-sm font-medium text-gray-700 mb-1">;
          Weekly Time Availability *;
        </label>;
        <textarea;
          name="weeklyTimeAvailability";
          value={formData.weeklyTimeAvailability};
          onChange={handleChange};
          required;
          rows={2};
          placeholder="e.g., 6-8 hours per week, available evenings and weekends";
          className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500";
        />;
      </div>;

      <div>;
        <label className="block text-sm font-medium text-gray-700 mb-2">;
          Equipment Access (select all that apply);
        </label>;
        <div className="grid grid-cols-1 md:grid-cols-2 gap-2">;
          {equipmentOptions.map(equipment => (;
            <label key={equipment} className="flex items-center">;
              <input;
                type="checkbox";
                checked={formData.equipmentAccess.includes(equipment)};
                onChange={(e) => handleCheckboxChange('equipmentAccess', equipment, e.target.checked)};
                className="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded";
              />;
              <span className="ml-2 text-gray-700">{equipment}</span>;
            </label>;
          ))};
        </div>;
      </div>;

      <div className="flex justify-between pt-6 border-t">;
        <button;
          type="button";
          onClick={onBack};
          className="px-6 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500";
        >;
          Back;
        </button>;
        <button;
          type="submit";
          disabled={isSubmitting};
          className="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed";
        >;
          {isSubmitting ? 'Saving...' : 'Continue to Step 2'};
        </button>;
      </div>;
    </form>;
  );
}
